### ISSUE TITLE
您好，方便告知一下高的数据是如何获取的吗？

### ISSUE THREAD

**Issue by nimysan** [bjwa2020/coronavirus#1]
我需要做一个应用给公司内部，提供基于酒店地址获取周边3公里内有感染的小区。请问您的高德数据是如何获到的？ 方便告知吗？

可以直接我邮箱 234aini@163.com 十分感谢。

**Comment by bjwa2020** [comment]
高德数据来自官方发布数据，大概2000条数据左右，目前没有完全的数据，如果有需要，请直接联系高德疫情地图官方索取相应数据。
